# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5488777e1c87e67d5145e3ea8d74b026212da94c3868a30ef8c2dc78fd6291e475478ea77f7629e334d45493fc78bdfefefcc9644fa16736af95433651e3451

test:
  secret_key_base: 4df621ae8e17cb104ccf71637d43d0e79a1c7ecb304f18e0eb4e1e302cefd789a7627292f6a6e8364957efcb535b8003aa48ee15a82d73c9f8b8721dd20a792f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
