# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd4ba92b41daacc8a9743a44440086bc50ed9ee487e5703ad8e7b6af9195193a625b7db7c76096be43ab757998bcf02a5865953da476df9d9266d000b947215c

test:
  secret_key_base: 95c78ac46d6cab6e735bceaa1d05355de01721101777bd4350d83dba07dd67a43452029854d01fc86fdb0e8b033a5c4af295083f859f3f051979d030e0690e7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
