# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e25048f0f284e782b625ce869fbf95cca59ebe22f8b1b80ce654e58a9a4cd66ec8c435bd0f27ba95fc655965a6719a769932c6e30459d45d488a7eb60dcd05bc

test:
  secret_key_base: 0b38b51f3addc836ea0f1f8b133308da5990380275dbd6711c6b769c6febf76605031b27b8231bf5ee230f429e0f62734ac7408cefadf22f94621d9f2b8a0e5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
